"""Added image for group chat and removed fileurl from user table

Revision ID: 8379cc4d7602
Revises: 17b9b1833494
Create Date: 2025-07-15 20:35:58.881527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8379cc4d7602'
down_revision: Union[str, Sequence[str], None] = '17b9b1833494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private_messages')
    op.add_column('chatroom', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('users', 'file_url')
    op.drop_column('users', 'file_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('chatroom', 'image')
    op.create_table('private_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('private_messages_receiver_id_fkey')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('private_messages_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('private_messages_pkey'))
    )
    # ### end Alembic commands ###
