"""add fileurl and type in messge module

Revision ID: e91b185dea20
Revises: 130736f16d54
Create Date: 2025-06-28 12:41:07.969466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91b185dea20'
down_revision: Union[str, Sequence[str], None] = '130736f16d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('messages', sa.Column('file_url', sa.String(), nullable=True))
    # op.add_column('messages', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'file_type')
    op.drop_column('messages', 'file_url')
    # ### end Alembic commands ###
